# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logSumExp <- function(x) {
    .Call('_cyclinbayes_logSumExp', PACKAGE = 'cyclinbayes', x)
}

log_dgamma <- function(x, a, b) {
    .Call('_cyclinbayes_log_dgamma', PACKAGE = 'cyclinbayes', x, a, b)
}

BayesSCLingam <- function(data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_og_tao, b_og_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter) {
    .Call('_cyclinbayes_BayesSCLingam', PACKAGE = 'cyclinbayes', data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_og_tao, b_og_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter)
}

BCD <- function(data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_og_tao, b_og_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter) {
    .Call('_cyclinbayes_BCD', PACKAGE = 'cyclinbayes', data_matrix, a_mu, b_mu, a_gamma, b_gamma, a_tao, b_tao, a_og_tao, b_og_tao, a_gamma_1, b_gamma_1, alpha, M, num_iter)
}

posterior_mean_adjacency <- function(Adjacency_matrix_samples, num_features) {
    .Call('_cyclinbayes_posterior_mean_adjacency', PACKAGE = 'cyclinbayes', Adjacency_matrix_samples, num_features)
}

posterior_mean_adjacency_threshold <- function(Adjacency_matrix_samples, num_features, threshold) {
    .Call('_cyclinbayes_posterior_mean_adjacency_threshold', PACKAGE = 'cyclinbayes', Adjacency_matrix_samples, num_features, threshold)
}

percentile_ci_causal_mat <- function(samples, lower, upper) {
    .Call('_cyclinbayes_percentile_ci_causal_mat', PACKAGE = 'cyclinbayes', samples, lower, upper)
}

hpd_ci_mat <- function(Causal_effect_matrix_list, cred_mass = 0.95) {
    .Call('_cyclinbayes_hpd_ci_mat', PACKAGE = 'cyclinbayes', Causal_effect_matrix_list, cred_mass)
}

